class DeptMapping

  def self.[](key)
    @@data[key]
  end

  @@data = {
    '0101' => {:dept => 'SAS - Anthropology', :address => '323 Museum'},
    '0103' => {:dept => 'SAS - Biology', :address => '102 Leidy Labs'},
    '0104' => {:dept => 'SAS - Chemistry', :address => 'Chemistry (Recep. Desk)'},
    '0105' => {:dept => 'SAS - Classical Studies', :address => '202 Logan Hall'},
    '0106' => {:dept => 'SAS - Economics', :address => '160 McNeil'},
    '0107' => {:dept => 'SAS - English', :address => '127 Fisher-Bennett Hall'},
    '0109' => {:dept => 'SAS - Earth and Environmental Science', :address => '254 B Hayden Hall'},
    '0110' => {:dept => 'SAS - German', :address => '745 Williams Hall'},
    '0111' => {:dept => 'SAS - History', :address => '208 College Hall'},
    '0112' => {:dept => 'SAS - History Of Art', :address => '107 Jaffe'},
    '0113' => {:dept => 'SAS - History and Sociology of Science', :address => '303 Logan Hall'},
    '0114' => {:dept => 'SAS - Linguistics', :address => '619 Williams Hall'},
    '0115' => {:dept => 'SAS - Math', :address => '4W1 Rittenhouse'},
    '0116' => {:dept => 'SAS - Music', :address => '202 Music'},
    '0117' => {:dept => 'SAS - Philosophy', :address => '433 Logan Hall'},
    '0118' => {:dept => 'SAS - Physics and Astronomy', :address => '2E1 Rittenhouse'},
    '0119' => {:dept => 'SAS - Political Science', :address => '217 Stiteler Hall'},
    '0120' => {:dept => 'SAS - Psychology', :address => 'B51 Solomon Labs'},
    '0121' => {:dept => 'SAS - Religious Studies', :address => '201 Logan Hall'},
    '0122' => {:dept => 'SAS - Romance Languages', :address => '521 Williams Hall'},
    '0123' => {:dept => 'SAS - South Asia Studies', :address => '820 Williams Hall'},
    '0124' => {:dept => 'SAS - Slavic Languages and Literature', :address => '745 Williams Hall'},
    '0125' => {:dept => 'SAS - Sociology', :address => '113 McNeil'},
    '0126' => {:dept => 'SAS - Criminology', :address => '483 McNeil'},
    '0127' => {:dept => 'SAS - Near Eastern Languages and Culture', :address => '847 Williams Hall'},
    '0128' => {:dept => 'SAS - East Asian Languages and Culture', :address => '847 Williams Hall'},
    '0602' => {:dept => 'NUR - Biobehavioral and Health Sciences', :address => '348 NEB'},
    '0603' => {:dept => 'NUR - Family and Community Health', :address => '354 NEB'},
    '1301' => {:dept => 'SEAS - Bioengineering', :address => '240 Skirkanich Hall'},
    '1302' => {:dept => 'SEAS - Chemical and Biomolecular Engineering', :address => '311A Towne Building'},
    '1303' => {:dept => 'SEAS - Computer and Information Science', :address => '302 Levine Hall'},
    '1304' => {:dept => 'SEAS - Electrical and Systems Engineering', :address => '203 Moore Building'},
    '1305' => {:dept => 'SEAS - Materials Science and Engineering', :address => '200 LRSM'},
    '1306' => {:dept => 'SEAS - Mechanical Engineering and Applied Mechanics', :address => '229 Towne Building'},
    '3200' => {:dept => 'Education', :address => 'GSE Division Office'}, 
    '3302' => {:dept => 'DES - Historic Preservation', :address => '115 Meyerson'},
    '3304' => {:dept => 'DES - Landscape Architecture', :address => '119 Meyerson'},
    '3305' => {:dept => 'DES - Fine Arts', :address => '100 Morgan, 114 Addams'},
    '3307' => {:dept => 'DES - Architecture', :address => '207 Meyerson'},
    '3308' => {:dept => 'DES - City Planning', :address => '127 Meyerson'},
    '3500' => {:dept => 'SP2 - Social Policy and Practice', :address => 'B35 Caster'},
    '3600' => {:dept => 'ASC - Communication', :address => '200 ASC'},
    '4051' => {:dept => 'SM-DN-Business Office', :address => 'Office'},
    '4102' => {:dept => 'BB-Biochemistry & Biophysics', :address => 'Office'},
    '4104' => {:dept => 'BE-Biostatistics & Epidemiology', :address => 'Office'},
    '4106' => {:dept => 'CD-Cell & Developmental Biology', :address => 'Office'},
    '4108' => {:dept => 'GE-Genetics', :address => 'Office'},
    '4112' => {:dept => 'MI-Microbiology', :address => 'Office'},
    '4114' => {:dept => 'NS-Neuroscience', :address => 'Office'},
    '4119' => {:dept => 'PH-Pharmacology', :address => 'Office'}, 
    '4121' => {:dept => 'PY-Physiology', :address => 'Office'},
    '4130' => {:dept => 'CB-Cancer Biology', :address => 'Office'},
    '4132' => {:dept => 'ME-Medical Ethics', :address => 'Office'},
    '4202' => {:dept => 'AN-Anesthesiology & Critical Care', :address => 'Office'},
    '4212' => {:dept => 'DE-Dermatology', :address => 'Office'},
    '4224' => {:dept => 'DM-Allergy and Immunology', :address => 'Office'},
    '4227' => {:dept => 'DM-Cardiovascular Medicine', :address => 'Office'},
    '4231' => {:dept => 'DM-Endocrinology, Diabetes and Metabolism', :address => 'Office'},
    '4235' => {:dept => 'DM-Experimental Therapeutics', :address => 'Office'},
    '4237' => {:dept => 'DM-Gastroenterology', :address => 'Office'},
    '4239' => {:dept => 'DM-General Internal Medicine', :address => 'Office'},
    '4243' => {:dept => 'DM-Geriatrics', :address => 'Office'},
    '4245' => {:dept => 'DM-Hematology/Oncology', :address => 'Office'},
    '4247' => {:dept => 'DM-Infectious Diseases', :address => 'Office'},
    '4249' => {:dept => 'GE-Medical Genetics', :address => 'Office'},
    '4255' => {:dept => 'DM-Medicine Central Admin', :address => 'Office'},
    '4257' => {:dept => 'DM-Pulmonary, Allergy and Critical Care', :address => 'Office'},
    '4259' => {:dept => 'DM-Renal-Electrolyte and Hypertension', :address => 'Office'},
    '4261' => {:dept => 'DM-Rheumatology', :address => 'Office'},
    '4269' => {:dept => 'DM-Division of Sleep Medicine', :address => 'Office'},
    '4270' => {:dept => 'DM-Hem Onc Cancer Biology', :address => 'Office'},
    '4302' => {:dept => 'EG-Emergency Medicine', :address => 'Office'}, 
    '4312' => {:dept => 'FM-Family Medicine', :address => 'Office'},
    '4322' => {:dept => 'NE-Neurology', :address => 'Office'},
    '4333' => {:dept => 'OB-Obstetrics & Gynecology', :address => 'Office'}, 
    '4352' => {:dept => 'OP-Ophthalmology', :address => 'Office'}, 
    '4372' => {:dept => 'OS-Orthopaedic Surgery', :address => 'Office'}, 
    '4382' => {:dept => 'OT-Otorhinilaryngology', :address => 'Office'},
    '4392' => {:dept => 'PE-Pediatrics', :address => 'Office'},
    '4412' => {:dept => 'PS-Psychiatry', :address => 'Office'},
    '4413' => {:dept => 'PS-Addictions', :address => 'Office'},
    '4414' => {:dept => 'PS-Anatomy-Chemistry', :address => 'Office'},
    '4415' => {:dept => 'PS-Behavioral Genetics', :address => 'Office'},
    '4416' => {:dept => 'PS-Behavioral Pharmacology', :address => 'Office'},
    '4417' => {:dept => 'PS-Biological Psychiatry', :address => 'Office'},
    '4418' => {:dept => 'PS-Bipolar Disorders', :address => 'Office'},
    '4419' => {:dept => 'PS-Center for Treatment of Anxiety', :address => 'Office'},
    '4420' => {:dept => 'PS-Center for Cognitive Therapy', :address => 'Office'},
    '4421' => {:dept => 'Depression Research', :address => 'Office'},
    '4422' => {:dept => 'PS-Geriatrics', :address => 'Office'},
    '4423' => {:dept => 'PS-Center for Mental Health Policy and Services Research', :address => 'Office'},
    '4425' => {:dept => 'PS-Brain Behavior Laboratory/ Neuropsychiatry Section', :address => 'Office'},
    '4426' => {:dept => 'PS-Center for Psychotherapy Research', :address => 'Office'},
    '4427' => {:dept => 'Sleep Center', :address => 'Office'},
    '4429' => {:dept => 'PS-Weight Disorders', :address => 'Office'},
    '4431' => {:dept => 'PS-Unit for Experimental Psychiatry', :address => 'Office'},
    '4432' => {:dept => 'PS-Affiliates', :address => 'Office'},
    '4433' => {:dept => 'PS-Other Psychiatry', :address => 'Office'},
    '4434' => {:dept => 'PS-Center for Neurobiology and Behavior', :address => 'Office'},
    '4435' => {:dept => 'PS-Center for Tobacco Research', :address => 'Office'},
    '4436' => {:dept => 'PS-Psychiatric and Medical Comorbidity', :address => 'Office'},
    '4438' => {:dept => 'PS-Psychiatry Business Office', :address => 'Office'},
    '4452' => {:dept => 'RA-Radiology', :address => 'Office'},
    '4482' => {:dept => 'RM-Rehabilitation and Physical Medicine', :address => 'Office'},
    '4492' => {:dept => 'RO-Radiation Oncology', :address => 'Office'},
    '4504' => {:dept => 'NY-Neurosurgery', :address => 'Office'},
    '4507' => {:dept => 'Trauma and Surgical Critical Care', :address => 'Office'},
    '4508' => {:dept => 'Urology', :address => 'Office'},
    '4521' => {:dept => 'PA-Pathology & Laboratory Medicine', :address => 'Office'},
    '5009' => {:dept => 'Van Pelt Library', :address => '3420 Walnut St'},
    '5102' => {:dept => 'DEN - Microbiology', :address => '244 Levy'},
    '5103' => {:dept => 'DEN - Biochemistry', :address => '541 Levy'},
    '5105' => {:dept => 'DEN - Oral Medicine', :address => '211 Schattner'},
    '5106' => {:dept => 'DEN - Preventative & Restorative Services', :address => '201C Hamilton Village'},
    '5107' => {:dept => 'DEN - Pathology', :address => '328-A Levy'},
    '5108' => {:dept => 'DEN - Orthodontics', :address => 'E-3 Evans'},
    '5110' => {:dept => 'DEN - Anatomy & Cell Biology', :address => '427 Levy'},
    '5112' => {:dept => 'DEN - Endodontics', :address => 'W-5 Evans'},
    '5113' => {:dept => 'DEN  -Periodontics', :address => 'W-1 Evans'},
    '5117' => {:dept => 'DEN - Oral Surgery/Pharmacology', :address => '100 Schattner'},
    '5802' => {:dept => 'VET - Animal Biology', :address => 'Vet Library'},
    '5803' => {:dept => 'VET - Pathobiology', :address => 'Vet Library'},
    '5804' => {:dept => 'VET - Clinical Studies - Philadelphia Campus', :address => 'Vet Library'},
    '5805' => {:dept => 'VET - Clinical Studies - New Bolton Campus', :address => 'Vet Library'}
  }

end
