version: "3.8"

services:
  app:
    build:
      args:
        RAILS_ENV: development
      target: development
    environment:
      APP_UID: ${CURRENT_UID:-1000}
      APP_GID: ${CURRENT_GID:-1000}
    volumes:
      - ${PWD}:/home/app
