version: "3.8"

services:
  app:
    build:
      args:
        RAILS_ENV: production
      context: .
      target: production
    env_file:
      - ".env"

  nginx:
    image: gitlab.library.upenn.edu/franklin/franklinforms-nginx:aee188f1
    ports:
      - "80:80"
    depends_on:
      - app
