version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6
  gitleaks: upenn-libraries/gitleaks@0.1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.1
      - image: quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1}
        environment:
          SECRET_KEY_BASE: x
    steps:
      - run:
          name: Smoke Test Container
          command: |
            wget \
              -q -t 5 --retry-connrefused -O /dev/null \
              http://localhost:80/redir/help

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/franklinforms
          tag: ${CIRCLE_SHA1}
          extra_build_args: >-
            -t quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1:0:7}
            --label "edu.upenn.library.build-system=circleci"
            --label "edu.upenn.library.circleci.build-number=${CIRCLE_BUILD_NUM}"
            --label "edu.upenn.library.circleci.build-timestamp=$(date -uIs)"
            --label "edu.upenn.library.circleci.build-url=${CIRCLE_BUILD_URL}"
            --label "edu.upenn.library.circleci.git-branch=${CIRCLE_BRANCH}"
            --label "edu.upenn.library.circleci.git-commit=${CIRCLE_SHA1}"
            --label "edu.upenn.library.circleci.git-repo-url=${CIRCLE_REPOSITORY_URL}"
            --label "edu.upenn.library.circleci.workflow-id=${CIRCLE_WORKFLOW_ID}"
      - test:
          requires:
            - docker-publish/publish
