version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.1
      - image: quay.io/upennlibraries/franklinforms:circleci.7
        environment:
          SECRET_KEY_BASE: x
    steps:
      - run:
          name: Smoke Test Container
          command: |
            wget \
              -q -t 5 --retry-connrefused -O /dev/null \
              http://localhost:80/redir/help

workflows:
  build_and_test:
    jobs:
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/franklinforms
          tag: circleci.${CIRCLE_BUILD_NUM}
      - test:
          requires:
            - docker-publish/publish
