version: 2.1

# Default slack config
default-slack-config:
  &default-slack-config
  channel: franklin-notification
  webhook: ${SLACK_WEBHOOK}

orbs:
  docker: circleci/docker@1.3.0
  gitleaks: upenn-libraries/gitleaks@0.1.0
  slack: circleci/slack@3.4.2

jobs:
  build_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Set Environment Variables for Slack Notification
          command: |
            echo "export GIT_COMMIT_DESC='$(git --git-dir $HOME/project/.git log --format=%B -n 1 $CIRCLE_SHA1)'" >> $BASH_ENV
            echo "export GIT_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>" >> $BASH_ENV
            source $BASH_ENV
      - docker/check:
          registry: quay.io
      - docker/build:
          extra_build_args: >-
            --label "edu.upenn.library.build-system=circleci"
            --label "edu.upenn.library.circleci.build-number=${CIRCLE_BUILD_NUM}"
            --label "edu.upenn.library.circleci.build-timestamp=$(date -uIs)"
            --label "edu.upenn.library.circleci.build-url=${CIRCLE_BUILD_URL}"
            --label "edu.upenn.library.circleci.git-branch=${CIRCLE_BRANCH}"
            --label "edu.upenn.library.circleci.git-commit=${CIRCLE_SHA1}"
            --label "edu.upenn.library.circleci.git-repo-url=${CIRCLE_REPOSITORY_URL}"
            --label "edu.upenn.library.circleci.workflow-id=${CIRCLE_WORKFLOW_ID}"
          image: upennlibraries/franklinforms
          registry: quay.io
          tag: "${CIRCLE_SHA1},${CIRCLE_SHA1:0:7}"
      - docker/push:
          image: upennlibraries/franklinforms
          registry: quay.io
          tag: "${CIRCLE_SHA1},${CIRCLE_SHA1:0:7}"
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Docker build failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
          success_message: ":tada: Docker build succeeded! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
  push_image:
    executor: docker/docker
    steps:
      - run:
          name: Set Environment Variables for Slack Notification
          command: |
            echo "export GIT_COMMIT_DESC='$(git --git-dir $HOME/project/.git log --format=%B -n 1 $CIRCLE_SHA1)'" >> $BASH_ENV
            echo "export GIT_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>" >> $BASH_ENV
            source $BASH_ENV
      - docker/push:
          image: upennlibraries/franklinforms
          registry: quay.io
          tag: "${CIRCLE_SHA1},${CIRCLE_SHA1:0:7}"
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Docker publish failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
          success_message: ":tada: Docker publish succeeded! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
  smoke_test:
    docker:
      - image: circleci/ruby:2.6.1
      - image: quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1}
    environment:
      GIT_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>
      SECRET_KEY_BASE: x
    steps:
      - run:
          name: Smoke Test
          command: |
            wget \
              -q -t 5 --retry-connrefused -O /dev/null \
              http://localhost:80/redir/help
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Smoke Test failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>"

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - build_image:
          context: quay.io
          requires:
            - gitleaks/check_local
      - smoke_test:
          requires:
            - build_image
      - push_image:
          context: quay.io
          requires:
            - smoke_test
