version: 2.1

# Default slack config
default-slack-config:
  &default-slack-config
  channel: franklin-notification
  webhook: ${SLACK_WEBHOOK}

orbs:
  docker: circleci/docker@1.3.0
  gitleaks: upenn-libraries/gitleaks@0.1.0
  slack: circleci/slack@3.4.2

jobs:
  build_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Set Environment Variables for Slack Notification
          command: |
            echo "export GIT_COMMIT_DESC='$(git --git-dir ~/project/.git log --format=%B -n 1 $CIRCLE_SHA1)'" >> $BASH_ENV
            echo "export GIT_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>" >> $BASH_ENV
            source $BASH_ENV
      - docker/check:
          registry: quay.io
      - docker/build:
          extra_build_args: >-
            --label "edu.upenn.library.build-system=circleci"
            --label "edu.upenn.library.circleci.build-number=${CIRCLE_BUILD_NUM}"
            --label "edu.upenn.library.circleci.build-timestamp=$(date -uIs)"
            --label "edu.upenn.library.circleci.build-url=${CIRCLE_BUILD_URL}"
            --label "edu.upenn.library.circleci.git-branch=${CIRCLE_BRANCH}"
            --label "edu.upenn.library.circleci.git-commit=${CIRCLE_SHA1}"
            --label "edu.upenn.library.circleci.git-repo-url=${CIRCLE_REPOSITORY_URL}"
            --label "edu.upenn.library.circleci.workflow-id=${CIRCLE_WORKFLOW_ID}"
          image: upennlibraries/franklinforms
          registry: quay.io
          tag: "${CIRCLE_SHA1}"
      - run:
          name: Save Docker Build
          command: |
            mkdir -p ~/image
            docker save -o ~/image/franklinforms_image.tar quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1}
      - persist_to_workspace:
          root: ~/image
          paths:
            - franklinforms_image.tar
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Docker build failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
          success_message: ":tada: Docker build succeeded! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
  rspec_test:
    executor: docker/docker
    environment:
      GIT_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/image
      - run:
          name: Load previously built docker image
          command: docker load -i ~/image/franklinforms_image.tar
      - run:
          name: Start Docker Container
          command: docker run -d -e SECRET_KEY_BASE=x --name franklinforms quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1}
      - run:
          name: Run RSpec Test
          command: docker exec franklinforms /bin/bash -c "~/.rbenv/shims/rspec"
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: RSpec test failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>"
          success_message: ":tada: RSpec test passed!"
  smoke_test:
    executor: docker/docker
    environment:
      GIT_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/image
      - run:
          name: Load previously built docker image
          command: docker load -i ~/image/franklinforms_image.tar
      - run:
          name: Start Docker Container
          command: docker run -d -e SECRET_KEY_BASE=x --name franklinforms quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1}
      - run:
          name: Install wget inside container
          command: docker exec franklinforms /bin/bash -c "apt update && apt install -y wget"
      - run:
          name: Run Smoke Test
          command: docker exec franklinforms wget -q -t 5 --retry-connrefused http://localhost:80/redir/help -O /dev/null
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Smoke test failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>"
          success_message: ":tada: Smoke test passed!"
  push_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/image
      - run:
          name: Set Environment Variables for Slack Notification
          command: |
            echo "export GIT_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Load previously built docker image
          command: |
            docker load -i ~/image/franklinforms_image.tar
            docker image tag quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1} quay.io/upennlibraries/franklinforms:${CIRCLE_SHA1:0:7}
      - docker/check:
          registry: quay.io
      - docker/push:
          image: upennlibraries/franklinforms
          registry: quay.io
          tag: "${CIRCLE_SHA1},${CIRCLE_SHA1:0:7}"
      - slack/status:
          <<: *default-slack-config
          failure_message: ":red_circle: Docker push failed! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>"
          success_message: ":tada: Docker push succeeded! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>"

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - build_image:
          context: quay.io
          requires:
            - gitleaks/check_local
      - smoke_test:
          requires:
            - build_image
      - rspec_test:
          requires:
            - build_image
      - push_image:
          context: quay.io
          requires:
            - rspec_test
            - smoke_test
